export const LEVEL_SUPPORT_OVERLAY = '60'
export const LEVEL_ALERT = '50'
export const LEVEL_POPUP = '40'
export const LEVEL_NAV_MOBILE = '30'
export const LEVEL_NAV_MAIN = '20'
export const LEVEL_MAIN_OVERLAYS = '10'
export const LEVEL_MAIN = '0'
export const LEVEL_BACKGROUND = '-10'